docs/assets/firehose-grafana-dashboard.json

- reconfigured hosts to app in all the panels.
- fix some other panels accordingly.
- removed hidden fields in the dashboard.

chore: fix firehose grafana dashboard issue

---

build.gradle
src/main/resources/logback.xml

fixes the log level config param to LOG_LEVEL

fix: update the log level config param

---

docs/contribute/contribution.md

- fix missing links from the contribution guide line.

docs: fix missing references from contribution guide

---

env/local.properties

lets put all possible configuration  of all sinks in firehose into env/local.properties ( all lines commented) , so that any new user will just have to uncomment those lines and change the values,

chore: add sample configs

---

src/main/java/io/odpf/firehose/sink/jdbc/HikariJdbcConnectionPool.java
src/main/java/io/odpf/firehose/sink/jdbc/JdbcSinkFactory.java

- enable register mbeans for jdbc sink

config: enable register mbeans for jdbc sink

---

CHANGELOG.md
build.gradle

chore: bump up version to 0.1.1

---

src/main/java/io/odpf/firehose/sink/common/AbstractHttpSink.java
src/test/java/io/odpf/firehose/sink/http/HttpSinkTest.java

Change log:
- SatusCode = 0 is added for retry under the AbstractHttpSink.java
- Tests for new functionality under HttpSinkTest.java

refactor: handle response code zero for retry

---

src/main/java/io/odpf/firehose/sink/common/AbstractHttpSink.java
src/test/java/io/odpf/firehose/sink/http/HttpSinkTest.java

Change Log:
- handle null value for httpStatusLine and httpEntity

refactor: handle null value for httpStatusLine and httpEntity

---

build.gradle
src/main/java/io/odpf/firehose/consumer/GenericConsumer.java
src/main/java/io/odpf/firehose/sink/common/AbstractHttpSink.java
src/main/java/io/odpf/firehose/sink/grpc/client/GrpcClient.java
src/main/java/io/odpf/firehose/sink/jdbc/JdbcSink.java

Refactor:
- Remove newRelic library and its reference from firehose code

refactor: remove newRelic library and its references

---

docs/README.md
docs/reference/faq/index.md

1. adds an FAQ file to the Firehose Repository, with FAQs for the Blob Sink.
2. links the file in main `README.md` under the how to start section for easy visibility.

Draft: Add FAQs for Blob Sink: FAQ PR #1

---

docs/README.md
docs/reference/faq/index.md

* builds upon the FAQ section as created in the [FAQ PR # 1](https://github.com/odpf/firehose/pull/137)
* adds FAQs for BigQuery Sink and references them in the Table of Contents

Add FAQs for BigQuery Sink: FAQ PR #2

---

docs/README.md
docs/reference/faq/index.md

builds upon the FAQ section as created in the [FAQ PR # 2](https://github.com/odpf/firehose/pull/138)
adds FAQs for Redis Sink and references them in the Table of Contents

Add FAQs for Redis Sink: FAQ PR #3

---

docs/README.md
docs/reference/faq/index.md

builds upon the FAQ section as created in the [FAQ PR # 3](https://github.com/odpf/firehose/pull/139)
adds FAQs for JDBC Sink and references them in the Table of Contents

Add FAQs for JDBC Sink: FAQ PR #4

---

docs/README.md
docs/reference/faq/index.md

builds upon the FAQ section as created in the [FAQ PR # 4](https://github.com/odpf/firehose/pull/140)
adds FAQs for HTTP Sink and references them in the Table of Contents

Add FAQs for HTTP Sink: FAQ PR #5 

---

docs/reference/configuration.md
docs/reference/configuration/redis-sink.md
src/main/java/io/odpf/firehose/config/RedisSinkConfig.java
src/main/java/io/odpf/firehose/config/enums/RedisSinkDataType.java
src/main/java/io/odpf/firehose/sink/redis/dataentry/RedisKeyValueEntry.java
src/main/java/io/odpf/firehose/sink/redis/parsers/RedisKeyValueParser.java
src/main/java/io/odpf/firehose/sink/redis/parsers/RedisParserFactory.java
src/test/java/io/odpf/firehose/sink/redis/dataentry/RedisKeyValueEntryTest.java
src/test/java/io/odpf/firehose/sink/redis/parsers/RedisKeyValueParserTest.java
src/test/java/io/odpf/firehose/sink/redis/parsers/RedisParserFactoryTest.java

feature:add key value support for redis sink

---

src/main/java/io/odpf/firehose/sink/redis/dataentry/RedisHashSetFieldEntry.java
src/test/java/io/odpf/firehose/sink/redis/dataentry/RedisHashSetFieldEntryTest.java

fix: ttl not being set hasset redis

---

src/main/java/io/odpf/firehose/sink/redis/dataentry/RedisKeyValueEntry.java
src/test/java/io/odpf/firehose/sink/redis/dataentry/RedisKeyValueEntryTest.java

fix: ttl not being set for keyvalue redis

---

build.gradle
src/main/java/io/odpf/firehose/consumer/FirehoseConsumerFactory.java
src/main/java/io/odpf/firehose/sink/SinkFactory.java
src/main/java/io/odpf/firehose/sink/bigquery/BigQuerySinkFactory.java
src/main/java/io/odpf/firehose/sink/bigquery/handler/BigQueryClient.java
src/main/resources/logback.xml
src/test/java/io/odpf/firehose/sink/bigquery/handler/BQClientTest.java

Fixes: 
1. Send util.logging logs to logback. 
2. Common stencil and bigquery client for all the threads. 
3. adding sinkfactory

chore: logging fix with bigquery optimisations

---

build.gradle
docs/reference/configuration/blob-sink.md
src/main/java/io/odpf/firehose/config/S3Config.java
src/main/java/io/odpf/firehose/sink/blob/BlobSinkFactory.java
src/main/java/io/odpf/firehose/sink/common/blobstorage/BlobStorageFactory.java
src/main/java/io/odpf/firehose/sink/common/blobstorage/BlobStorageType.java
src/main/java/io/odpf/firehose/sink/common/blobstorage/s3/S3.java
src/main/java/io/odpf/firehose/sink/dlq/DlqWriterFactory.java
src/test/java/io/odpf/firehose/config/S3ConfigTest.java

Please describe what you added, and add a screenshot if possible.
That makes it easier to understand the change so we can :shipit: faster.

feat: blob s3 support

---

build.gradle
src/main/java/io/odpf/firehose/sink/bigquery/proto/ProtoUpdateListener.java

feat: upgrade stencil client version

---

docs/docs/reference/faq.md
docs/docs/sinks/http-sink.md
src/main/java/io/odpf/firehose/config/enums/HttpSinkRequestMethodType.java
src/main/java/io/odpf/firehose/sink/http/request/HttpRequestMethodFactory.java
src/test/java/io/odpf/firehose/sink/http/request/create/BatchRequestCreatorTest.java
src/test/java/io/odpf/firehose/sink/http/request/create/IndividualRequestCreatorTest.java

Signed-off-by: Deep Mistry <248.deep@gmail.com>
Added PATCH method support for HTTP sink

feat: patch method support for http sink

---

README.md
docs/docs/concepts/offsets.md

- Fix heading of offset documentation.
- Corrected link to contributing guide.

docs: fix heading and contribution link
